before_script:
    - python -v
    - pip install tornado
    
types:
    - build
    - test
    
build_app:
    type: build
    script: echo Building!
    
test_app:
    type: test
    script: python -v